### ISSUE TITLE
Using variables?

### ISSUE THREAD

**Issue by alexpriceonline** [zeit/styled-jsx#56] opened 2016-12-25 07:58 UTC
I thought I was being clever with my use of variables, but it seems to break the styles:

```JS
// colours.js
export const blue = opacity => `rgba(51, 77, 92, ${opacity})`;
```

```JS
// component.js
import { blue } from './colours.js';

const Foo = () => (
  <div>
    Hello world
    <style jsx>{`
      div {
        color: ${blue(1)};
      }
    `}</style>
  </div>
);
```

Is there a recommended way to use variables like this?

**Comment by nkzawa** [comment] 2016-12-25 08:55
Duplicate of https://github.com/zeit/styled-jsx/issues/25

**Closed by nkzawa** 2016-12-25 08:55 UTC
