### ISSUE TITLE
"Syntax Error: Bad character escape sequence" on windows while `npm run dev` for `/u` path pages

### ISSUE THREAD

**Issue by amio** [zeit/styled-jsx#253] opened 2017-06-30 07:48 UTC
How to reproduce:

- On Windows 10
- Clone this repo: [styled-jsx-u-debug](https://github.com/amio/styled-jsx-u-debug)
- `npm run dev`

![image](https://user-images.githubusercontent.com/215282/27725648-ede62614-5d3c-11e7-9d15-e1a2c956dbf0.png)

if change [this line](https://github.com/amio/styled-jsx-u-debug/blob/master/pages/user.js#L8):
```
color: ${FONT_COLOR};
```
to
```
color: blue;
```
the error is gone.

GUESS:

It looks like a problem with the babel plugin, which get paths on windows like `C:\project\pages\user.js`, and the `\u` in the path cause character escaping.

**Comment by smiled0g** [comment] 2017-07-13 17:17
I'd like to confirm this problem. It looks like your hypothesis is correct @amio I never encountered any problem until I introduced a file with `\u` in the path 

![capture](https://user-images.githubusercontent.com/891585/28178700-8e7dc356-6829-11e7-8f78-752fd3c12e33.PNG)

**Comment by giuseppeg** [comment] 2017-07-18 12:26
I don't want a Windows machine, do you guys want to help out / try to fix this ?

**Comment by smeijer** [comment] 2018-02-26 14:05
Any workaround other than renaming my `/ui` dir?

**Comment by smeijer** [comment] 2018-03-01 11:21
Looks like `angular-meteor` had the same issue a while ago. They seem to have it fixed though.

https://github.com/Urigo/angular-meteor/issues/1770

**Comment by smeijer** [comment] 2018-03-01 12:56
I've noticed it only impacts files with `interpolated dynamic props`. Files without dynamic props can still be imported.

**Comment by giuseppeg** [comment] 2018-03-09 12:50
@smeijer can you provide a test case? a super simple Next.js app maybe?

**Comment by giuseppeg** [comment] 2018-03-09 12:53
@amio can you try without styled-jsx? Maybe it is an issue with Next.js

**Comment by smeijer** [comment] 2018-03-09 13:44
@giuseppeg, I'm experiencing the same bug in a Meteor project, and also in the Storybook stories. I'm not using Next.js at all.

**Comment by amio** [comment] 2018-03-10 01:50
@giuseppeg I found this from my client's environment, but for now I don't have a windows machine neither 😟

**Comment by giuseppeg** [comment] 2018-09-28 06:47
can you upgrade to styled-jsx v3.1.0 and let me know if this is still an issue?

**Comment by connorads** [comment] 2019-10-06 12:37
I tried to reproduce the issue on my Windows 10 machine but it worked fine.
- Could be my Windows 10 version is different? Some other difference in environment.
- Could it be that an issue in the dependency tree has been fixed? There's no `package-lock.json` in repo [styled-jsx-u-debug](https://github.com/amio/styled-jsx-u-debug) for reproducing the issue. I'm not an expert in `npm` but feel like this could be why.

Another project fixed this issue by upgrading package with an unknown specific culprit.
- Maybe this issue is fixed already?
- Maybe it would be fixed if the packages were upgraded as per @giuseppeg

**Comment by connorads** [comment] 2019-10-06 12:46
**Update:**
I think we can close this issue.

I found a [commit](https://github.com/amio/styled-jsx-u-debug/commits/master) with `package-lock.json` in there and reproduced the issue.
![image](https://user-images.githubusercontent.com/10026538/66269381-a1fff280-e83f-11e9-87cb-b422f4fdf483.png)

When running `npm install` without a `package-lock.json` the issue is no longer there.
So I think it is an issue in the `npm` dependency tree that has since been fixed.
![image](https://user-images.githubusercontent.com/10026538/66269382-adebb480-e83f-11e9-81a3-bb39335cf677.png)

**Comment by giuseppeg** [comment] 2019-10-06 16:03
Thank you a lot for taking a look at this @connorads!!

**Closed by giuseppeg** 2019-10-06 16:03 UTC
Labels: bug, help wanted

**Comment by aorsten** [comment] 2019-10-29 15:09
Any idea which npm dependency might have caused this, @connorads ?
I'm experiencing the same issue in my NextJS project on Windows 10. 

In my case as well, the file is placed in ".../utils/MyFile.js". Changing to ".../test_utils/MyFile.js" fixed it.

**Comment by connorads** [comment] 2019-10-29 23:25
Nope sorry @aorsten
I'm guessing you've tried deleting 'package-lock.json' and/or updating your npm packages?

**Comment by aorsten** [comment] 2019-10-30 07:35
Yeah, I tried that - but it didn't resolve the issue.
