### ISSUE TITLE
Support multiple instances of <styled jsx> in one app

### ISSUE THREAD

**Issue by hanford** [zeit/styled-jsx#309] opened 2017-10-12 18:19 UTC
Hello! First of all, thank's everyone who's been working on `styled-jsx` .. `styled-jsx` and `Next.js` are a match made in heaven and are incredible easy / fun to use.

I have a somewhat interesting use case where I'm working on a UI library that is distributed via NPM using Lerna + yarn. I noticed a bug (bug may not be the correct work) .. with `styled-jsx` where when I have multiple instances of the component on a given page, the dynamic prop based styles aren't unique to a given component.

For Example, if I build a simple `<Row>` component that looks something like this

```js
export default class Row extends PureComponent {
  static propTypes = {
    tag: PropTypes.node,
    componentStyle: PropTypes.object,
    align: PropTypes.string,
    justify: PropTypes.string
  }

  static defaultProps = {
    tag: 'div',
    componentStyle: {},
    align: 'initial',
    justify: 'initial'
  }

  render () {
    const { componentStyle, align, justify } = this.props

    return (
      <this.props.tag style={{ ...componentStyle }} className='row'>
        {this.props.children}

        <style jsx>{`
          .row {
            display: flex;
            flex-direction: row;
            align-items: ${align};
            justify-content: ${justify};
          }
        `}</style>
      </this.props.tag>
    )
  }
}

```

In my code if I have multiple `<Row>`'s with different props, ie something like this:

```js
<Row justify='space-between'>...</Row>
..
<Row justify='space-around'>...</Row>
```

Then both `Row's ` will both generate a class like this
```css
.row {
  ...
  justify-content: space-around;
}
```

Here's an image:
![](http://d.pr/i/w4LzkX+)

I guess what I'm wondering is if there is any plans to support the use case of multiple `styled-jsx` instances on one page, as it would make component development much, much more straightforward. There is a similar issue with other lib's like styled-components.

**Comment by giuseppeg** [comment] 2017-10-18 08:26
the problem is with the tag `this.props.tag` being dynamic, right now those are not transpiled. There is a wip PR https://github.com/zeit/styled-jsx/pull/244 to fix that, I might finish it when I have a little free time

**Comment by giuseppeg** [comment] 2017-12-16 13:13
Duplicate of #147

**Closed by giuseppeg** 2017-12-16 13:13 UTC

**Comment by giuseppeg** [comment] 2017-12-16 14:02
@hanford I also read the Emotion issue and my answer would be, define styled-jsx in your packages as a peerDependency and install it only in the main app that consumes styled-jsx.
