### ISSUE TITLE
Space in calc is ignored

### ISSUE THREAD

**Issue by Larry850806** [zeit/styled-jsx#220] opened 2017-06-02 05:25 UTC
I'm using `styled-jsx@1.0.3`. I found `width: calc(20% + 503px)` was compiled to `width: calc(20%+503)`. The space between `20%` and `503px` disappear. `width: calc(20%+503)` is invalid syntax in Chrome. And there is no this problem in `styled-jsx@0.5.7`.

**Comment by giuseppeg** [comment] 2017-06-02 06:35
cc @thysultan

**Comment by thysultan** [comment] 2017-06-02 06:40
Can't reproduce, @Larry850806 can you post `width: calc(20% + 503px)` in the context it's used?

**Comment by thysultan** [comment] 2017-06-02 07:34
I think i know where this stems from, the minification process.

**Comment by thysultan** [comment] 2017-06-02 10:22
patched in v3.0.14

**Comment by giuseppeg** [comment] 2017-06-04 10:16
Fixed in #223

**Closed by giuseppeg** 2017-06-04 10:16 UTC
Labels: bug
