### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by timsuchanek** [zeit/styled-jsx#90] opened 2017-01-23 17:05 UTC
First of all, awesome tool!
We're using it together with TypeScript and it works like a charm.
However, `jsx` and `global` are no standard html attributes, so the React Typings don't include them and the TypeScript compiler throws errors.
That can easiliy be fixed with these 2 additions:
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...timsuchanek:patch-1
What are your ideas on it? Is there another way to make it work with TypeScript?
Thanks

**Comment by rauchg** [comment] 2017-01-23 17:34
Aren't people usually including something like `@types/styled-jsx`? Otherwise we have to support TS, Flow, etc whatever comes next

**Comment by giuseppeg** [comment] 2017-01-23 17:53
> Aren't people usually including something like @types/styled-jsx?

Yep flow, closure compiler and I suppose TS support external declarations

**Comment by timsuchanek** [comment] 2017-01-23 19:42
Yes, `@types/styled-jsx` would be the way to go, however in my understanding the current version of TypeScript doesn't support "merging of Interfaces in namespaces", which needs to be done, because the according interface of the `<style>` element in `@types/react` is in a namespace.
So I see as a current approach only adding it to the `@types/react` types until that merging issue is resolved.

**Comment by Hotell** [comment] 2017-01-23 21:11
sry for off topic, but how are u using it with typescript @timsuchanek  ? you are double transpiling? TS -> Babel ( because according to docs, you need babel styled-jsx plugin )

**Comment by timsuchanek** [comment] 2017-01-23 21:24
@Hotell Indeed, so first I'm transpiling with `"jsx": "preserve"` set in the .tsconfig and then running babel over it.
Using webpack that's just `babel-loader!awesome-typescript-loader`

**Comment by nikvm** [comment] 2017-02-16 21:55
That brings up the question if `styled-jsx` shouldn't be used like:

```jsx
import Style from 'styled-jsx/component'

const IAmRed = () => (
  <div>
    <p>I'm red</p>
    <Style>{` p { color: red; } `}</Style>
    <Style global>{` body { background: white; }`}</Style>
  </div>
)
```

Also the current implementation feels nicer. This might be more according to React standards and doesn't interfere with native elements.

**Comment by rauchg** [comment] 2017-02-17 04:01
@nikvm the issue is that that makes me think the component is standalone, but in reality it requires transpilation. It's actually _less_ intuitive.

**Comment by phtoussaint** [comment] 2017-03-02 08:49
I took advice from @timsuchanek  and simply put this in my code, in `typings/styled-jsx.d.ts`

```typescript
import 'react'
// Augmentation of React
declare module "react" {
  interface HTMLProps<T> {
    jsx?: boolean;
    global?: boolean;
  }
}
```

It works like a charm!

**Comment by jvoros** [comment] 2017-05-18 04:22
Thanks for the explanation @timsuchanek. Couldn't figure out why it wasn't working, reconfigured webpack to let babel do the jsx transpiling, not awesome-typescript-loader, like you described, working great now.

**Comment by smeijer** [comment] 2017-07-26 12:07
Regarding to typescript and `styled-jsx`, any idea how to fix this one?

```
<style jsx>
</style>

Error:(38, 16) TS2339:Property 'jsx' does not exist on type 
  'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
```

**Comment by smeijer** [comment] 2017-07-26 13:29
I was able to fix it with:

```ts
// custom.d.ts
import 'react';

declare module 'react' {
  interface StyleHTMLAttributes<T> extends React.HTMLAttributes<T> {
    jsx?: boolean;
    global?: boolean;
  }
}
```

**Comment by johhansantana** [comment] 2017-08-09 22:07
hmm I can't seem to get this working, not sure if it's the same issue but i get the following errors:

![1](https://user-images.githubusercontent.com/9933887/29146094-9ae02378-7d2d-11e7-9fa4-24793de22733.png)

**Comment by tomitrescak** [comment] 2017-10-16 11:37
@nikvm can it actually be used like that? I’m searching for a solution that does not require Babel and can go pure Typescript

**Comment by naffiq** [comment] 2017-11-06 19:50
@smeijer 

Hi, thanx for the fix, but I can't make it work.

My `tsconfig.json` is:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "jsx": "react",
        "allowJs": true,
        "typeRoots": [ 
            "node_modules/@types",
            "./typings"
        ]
    },
    "exclude": [
        "next.config.js"
    ]
}
```

I'm very fresh with typescript, sorry for bothering

**Comment by littlepoolshark** [comment] 2017-12-07 09:04
Now,I have resolve the error "Property 'jsx' does not exist on type ".But I  still can not make styled-jsx work with the awesome-typescript-loader.My webpack.config.js is showed below:` {
                test:/\.tsx?$/,
                use:[
                    "babel-loader",
                    "awesome-typescript-loader"
                ]
            }`

**Comment by R1ZZU** [comment] 2017-12-14 11:32
check out DefinitelyTyped/DefinitelyTyped#22181

**Comment by R1ZZU** [comment] 2017-12-26 22:05
added more typings in [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22516). Would appreciate @giuseppeg's review

extension of react `style` Element supporting `jsx` and `global` attributes is already available in `@types/styled-jsx` package

**Comment by R1ZZU** [comment] 2018-01-03 09:41
@giuseppeg This issue could be closed as DefinitelyTyped/DefinitelyTyped#22516 was merged and typings already available under `@types/styled-jsx`

**Comment by 1kohei1** [comment] 2018-01-12 15:30
Hi, I installed `@types/styled-jsx` and errors is gone. However, the style is not reflected in the next app. Does someone help me figure this out, please🙏 If I add `global`, style is reflected, but I would like to avoid.

My tsconfig.json is:
```
{
  "compilerOptions": {
    "jsx": "react-native",
    "module": "commonjs",
    "strict": true,
    "target": "es2017",
    "sourceMap": true
  }
}
```

The component `jsx` style is not reflected is this: https://github.com/1kohei1/sd-scheduler/blob/master/front/components/MyLayout.tsx

**Comment by a-ignatov-parc** [comment] 2018-01-12 15:41
@1kohei1 you are trying to pass `className` to components and not DOM elements. `styled-jsx` doesn't transform such things. But you can use this [workaround](https://github.com/zeit/styled-jsx/#styling-third-parties--child-components-from-the-parent) to pass them explicitly.

**Comment by 1kohei1** [comment] 2018-01-14 01:04
@a-ignatov-parc Ok! Thank you! I decided to apply style by `style` tag!

**Comment by Matityahul** [comment] 2018-01-31 17:20
@djskinner, to solve the *specific* error you got, you just need to change the follow:
from: 
```javascript
// styles.ts
import css from "styled-jsx/css";

// component.tsx
import styles from "./styles";
```
to: 
```javascript
// styles.ts
import * as css from "styled-jsx/css";

// component.tsx
import * as styles from "./styles";
```
But still it will not work for other reason. I get the follow error from styled-jsx/css:
"Error: styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled."

I couldn't resolve it.
Has anyone managed to use styled-jsx with typescript and CSS in separate file?

**Comment by ahoyahoy** [comment] 2018-02-07 06:54
How write this for Inferno?

```import 'react';

declare module 'react' {
  interface StyleHTMLAttributes<T> extends React.HTMLAttributes<T> {
    jsx?: boolean;
    global?: boolean;
  }
}```

**Comment by giuseppeg** [comment] 2018-03-09 12:59
@R1ZZU can you help these folks?

**Comment by bensaufley** [comment] 2018-04-06 17:39
Following up on the first issue, `exports.default` vs `export = css` at DefinitelyTyped, I'm realizing that I had conflated the output of my `styles.ts` and the output of `styled-jsx/css`, which … doesn't actually exist as anything more than a hook that says "transpile this". So I think my original PR, to satisfy TypeScript's type checking, is correct.

**Comment by leebenson** [comment] 2018-05-06 20:57
@timsuchanek - Just want to say a belated thanks for your `"jsx": "preserve"` tip. I'm using Typescript + Webpack + Babel locally, and couldn't figure out why my other plugins were firing, but not styled-jsx.

Of course, it was because Typescript was already transforming JSX -> `React.createElement`, so this plugin didn't have the original JSX to parse.

IMO, this could do with being featured under a 'Using with Typescript' section in the readme.

**Comment by James-Harris14** [comment] 2018-07-28 02:40
@leebenson @timsuchanek Could you guys please describe the process you are using to transpile with `"jsx": "preserve"`?

I'm using `"jsx": "preserve"` in my `tsconfig.json` and my webpack config uses the loader like this:
```
config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loaders: 'babel-loader!awesome-typescript-loader'
    });
```

However I'm still getting errors:
```
WARNING in ./src/components/App/App.stories.tsx
storybook_1  | Module build failed (from ./node_modules/babel-loader/lib/index.js):
storybook_1  | SyntaxError: Unexpected token (9:70)
storybook_1  |
storybook_1  |    7 | import ApolloProviderContainer from 'containers/ApolloProviderContainer';
storybook_1  |    8 | import App from './App';
storybook_1  | >  9 | storiesOf('Welcome', module).add('to Storybook', function () { return <Welcome showApp={linkTo('Button')}/>; });
storybook_1  |      |                                                                       ^
storybook_1  |   10 | storiesOf('Button', module)
storybook_1  |   11 |     .add('with text', function () { return <Button onClick={action('clicked')}>Hello Button</Button>; })
storybook_1  |   12 |     .add('with some emoji', function () { return (<Button onClick={action('clicked')}>
storybook_1  |
storybook_1  |  @ ./src sync stories\.tsx?$ ./components/App/App.stories.tsx
storybook_1  |  @ ./.storybook/config.js
storybook_1  |  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

I need `"jsx": "preserve"` because otherwise the styled jsx won't apply to my components.

Any help is appreciated.

**Closed** 2018-09-28 06:52 UTC
Labels: enhancement, help wanted

**Comment by SwordsmanYao** [comment] 2019-05-10 09:14
global.d.ts
`
declare namespace JSX {
  interface IntrinsicElements {
    style: {
      jsx: boolean;
    };
  }
}
`

**Comment by eric-burel** [comment] 2020-03-03 15:21
Hi, I am hitting this issue with wrong scoping: `https://spectrum.chat/styled-jsx/general/storybook-next-js-styled-jsx-styles-not-scoped-to-component~8a63d2a1-6b05-4a27-b839-c4a903eb6f43`.

`style jsx` is just converted to a local style tag, so style will be unscoped :/

**Comment by cmnstmntmn** [comment] 2020-04-12 21:53
hei, i'm using CRA typescript template.

i've tried `"jsx": "preserve"`, and this

```ts
// custom.d.ts
import "react";

declare module "react" {
  interface StyleHTMLAttributes<T> extends React.HTMLAttributes<T> {
    jsx?: boolean;
    global?: boolean;
  }
}
```

however i'm getting

```
Warning: Received `true` for a non-boolean attribute `jsx`.

If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.
...
```

any other workarounds?
ty

**Comment by el-ethan** [comment] 2020-12-22 16:52
@cmnstmntmn I struggled with the same issue. I am using create-react-library, so my solution might work for you as well. For me, the combination that seemed to work was the two fixes that you use above, plus adding a `.babelrc` to the root of my project with the following contents:

```
{
  "plugins": ["styled-jsx/babel"]
}
```

Hope this works for you as well. I spent many hours banging my head against this one before coming up with something that appears to work...

**Comment by fdlmhmd29** [comment] 2021-02-22 13:42
Thank you @smeijer 
>I was able to fix it with:
> 
> ```ts
> // custom.d.ts
> import 'react';
> 
> declare module 'react' {
>   interface StyleHTMLAttributes<T> extends React.HTMLAttributes<T> {
>     jsx?: boolean;
>     global?: boolean;
>   }
> }
> ```
