### ISSUE TITLE
It's consoled too many logs.How to shut down it?

### ISSUE THREAD

**Issue by longge0516** [zeit/styled-jsx#514] opened 2018-10-29 03:36 UTC
👋 friend. Welcome to styled-jsx and thanks for contributing!

⚠️ IMPORTANT ⚠️

If you need help or have a question about styled-jsx please ask it on Spectrum https://spectrum.chat/styled-jsx or join our Slack community at https://zeit.chat and ask it in the `#next` channel.

Before you open a new issue please take a look at our [**Frequent Asked Questions**](https://github.com/zeit/styled-jsx#faq) and [**open issues**](https://github.com/zeit/styled-jsx/issues).

Remember, often time asking in chat or looking at the FAQ/issues can be *faster than waiting for us to reply to a new issue**.

If you are here to report a bug or request a feature please remove this introductory section and fill out the information below!

---

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1.
2.

#### Environment (include versions)

* OS:
* Browser:
* styled-jsx (version):

**Comment by giuseppeg** [comment] 2018-10-29 09:22
duplicate of #480

**Closed by giuseppeg** 2018-10-29 09:22 UTC
