### ISSUE TITLE
Editing style via DevTools breaks all styles (Next 7)

### ISSUE THREAD

**Issue by atomiks** [zeit/styled-jsx#513] opened 2018-10-26 08:21 UTC
I'm using `styled-jsx` with Next.js 7, everything default. I'm not sure if I'm doing something wrong with the Layout/component nesting to cause this..

#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

Editing a CSS property via Chrome DevTools completely resets/breaks the whole CSS.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

`pages/index.js` minimal reproduction

```jsx
import { Component } from 'react'
import Head from 'next/head'

const Layout = ({ children }) => (
  <div>
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
    </Head>
    {children}
    <style jsx global>{`
      html {
        box-sizing: border-box;
      }
      *,
      *::before,
      *::after {
        box-sizing: inherit;
      }
      body {
        margin: 0;
        font-family: 'Avenir Next', Avenir, 'Helvetica Neue', Helvetica, Arial,
          sans-serif;
        background-color: #0e0c1d;
      }
    `}</style>
  </div>
)

const Header = ({ children }) => (
  <header className="header">
    {children}
    <style jsx>{`
      .header {
        background: radial-gradient(circle at 20% 20%, #262a49, #2b193b);
        color: #a2b9ff;
      }
    `}</style>
  </header>
)

export default class Homepage extends Component {
  render() {
    return (
      <Layout>
        <Header>
          <h1>hello</h1>
          <style jsx>{`
            h1 { 
              color: pink ;
            } 
          `}</style>
        </Header>
      </Layout>
    )
  }
}
```

When you edit the `h1`'s `color` via DevTools, the CSS gets completely reset.

#### What is the expected behavior?

Doesn't reset/remove the CSS rules

#### Environment (include versions)

* OS: macOS 10.14
* Browser: Chrome 70
* styled-jsx (version): Next.js 7.0.2 (not sure)

#### Did this work in previous versions?

Haven't used it before

**Comment by giuseppeg** [comment] 2018-10-28 08:37
those styles are not persisted, so probably when the component re-renders they are lost

**Comment by giuseppeg** [comment] 2018-10-28 08:37
closing because this doesn’t seem like an issue with styled-jsx

**Closed by giuseppeg** 2018-10-28 08:37 UTC

**Comment by stevenhao** [comment] 2018-12-06 02:17
i have the same issue

**Comment by stevenhao** [comment] 2018-12-06 02:18
To clarify: the styles that are lost are the ones specified in the source code via `<style jsx>`.

**Comment by NeatNit** [comment] 2019-09-16 16:38
Can I ask that this be reopened?

This *is* an issue with styled-jsx and the way it gets applied in Next applications. It has to do with the way Chrome handles style changes made by the user inside the dev tools.

I have not tried with other browsers, but Chrome is the most popular browser and the one most often used for development (correct me if I'm wrong), so the behaviour in Chrome should be considered important.

**Disclaimer: I don't actually know how Chrome works, the following is pure conjecture based on the user experience when using Chrome dev tools and nothing else. I also don't know how styled-jsx works, but can see its behaviour within Chrome in the relevant context.**

Chrome applies style changes by inserting them into the <style> tag or .css file in memory, then re-parsing that tag/file like normal. If you add a rule, it adds it as a new line; if you disable a rule (using the checkbox next to it), it gets commented out `/* like: this; */`. After it's made the necessary changes, the style gets applied "naturally" since it's where CSS always is.

The problem is that the way styled-jsx works, is that there is no proper CSS anywhere in memory. I don't know how it applies the style, but if you click the name in the corner you can see where the style rule is:

![image](https://user-images.githubusercontent.com/2400026/64975754-6913d400-d8b8-11e9-8e2b-3f5833905137.png)

Clicking it leads to this, which is not valid CSS:

![image](https://user-images.githubusercontent.com/2400026/64975816-91033780-d8b8-11e9-82d0-b909150e80ae.png)

Therefore, as soon as I make any change (e.g. disable or change font-size), it fails to make the edit in the style tag, then fails to parse it, then simply doesn't know what to do with it at all.

**Comment by jkjustjoshing** [comment] 2019-12-04 21:49
@giuseppeg this is still a very annoying issue when developing with styled-jsx. Can this ticket be reopened?

**Comment by NeatNit** [comment] 2019-12-04 21:57
> @giuseppeg this is still a very annoying issue when developing with styled-jsx. Can this ticket be reopened?

I'm not sure they're seeing these comments, perhaps you should open a new issue asking for this one to be reopened.

I'm no longer using Next.js or styled-jsx (at least not for the time being) so I don't want to open it myself.
