### ISSUE TITLE
Error "insertRule` accepts only strings" when using with styled-components

### ISSUE THREAD

**Issue by jdolinski1** [zeit/styled-jsx#530] opened 2018-12-02 22:54 UTC
#### What is the current behavior?

1. Get `with-styled-components` example (https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) 
2. Add `<styled jsx tag` to the index.js file so you got something like:
```
export default () => (
    <div>
        <h1>hello</h1>
        <style jsx={true} global={true}>
            {`
                h1 {
                    color: red;
                }
            `}
        </style>
    </div>
)

```

5. Error appears:
```
StyleSheet: `insertRule` accepts only strings.
```

6.  When i remove the ` "styled-components"` plugin from `.babelrc`, everything works fine.

#### What is the expected behavior?
Styled-jsx tags should work with styled-components + babel-plugin-styled-components in stack.

#### Environment (include versions)

* OS: OSX 10.13.4
* Browser: Chrome 70.0.3538.102 
* styled-jsx (version): `3.1.0`

#### Did this work in previous versions?
IIRC this was working in my older project with Next.js `6.1.1`.

**Comment by ssypi** [comment] 2018-12-04 23:54
Not sure if the problem is with styled-jsx, [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components) or where, but installing babel-plugin-styled-components version 1.8.0 seems to fix this problem. 1.9.0 doesn't work or the current 1.9.2.

**Comment by tomanagle** [comment] 2018-12-05 17:07
I've been trying to figure this out for 3 days now. If you remove the jsx tag from your <style> tag, it seems to work. 

So change:
 ```
<style jsx>
          {`
            .nav-container {
              background-color: #fff;
              padding-top: 0.375rem;
              padding-bottom: 0.375rem;
              border-bottom: solid 1px #333;
            }
          `}
        </style>
```

To:
 ```
<style>
          {`
            .nav-container {
              background-color: #fff;
              padding-top: 0.375rem;
              padding-bottom: 0.375rem;
              border-bottom: solid 1px #333;
            }
          `}
        </style>
```

**Comment by jsve** [comment] 2018-12-07 15:13
I'm having the same issu as the @jdolinski1 

In desperation I have tried the following (with next.js 7.0.2):
- styled-components@4.1.2 + babel-plugin-styled-components@1.9.2
- styled-components@4.1.2 + babel-plugin-styled-components@1.8.0
- styled-components@4.0.0 + babel-plugin-styled-components@1.9.2
- styled-components@4.0.0 + babel-plugin-styled-components@1.8.0
- styled-components@3.1.0 + babel-plugin-styled-components@1.8.0

if i remove babel-plugin-styled-components from my babelrc, the error goes away. Same thing if i replace 'style jsx' with 'style' as @tomanagle suggested, but not sure how that affect the rest of my code. Is jsx not needed?

**Comment by ssypi** [comment] 2018-12-07 15:31
@jsve Are you sure the versions were correctly installed and no caches or something was left behind? I ask because I had this problem, but when I installed babel-plugin-styled-componenta@1.8.0 it disappeared, I had styled-components@4.1.2 and the currently latest nextjs, 7.2 or is it 7.0.2.

I’m not sure but I think removing the jsx attribute will stop the prefixing of classes so it becomes global instead of contained in the component.

**Comment by jsve** [comment] 2018-12-07 15:38
pretty sure. tried again now and ran `npm cache clean --force` and then `npm install` but with same error message. Is there something other i can try?

**Comment by shYkiSto** [comment] 2018-12-13 04:47
That's related to changes introduced in https://github.com/styled-components/babel-plugin-styled-components/pull/172 to support this "new" `css` prop API: https://www.styled-components.com/docs/api#css-prop

What happens is that component generated from `<style jsx />` gets transpiled by the styled-components babel plugin as styled-jsx uses the `css` prop internally. 

I would suggest this conflict should be resolved in styled-jsx as it seem to be by far the most easiest change:
https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L415
https://github.com/zeit/styled-jsx/blob/master/src/_constants.js#L4

Thoughts?

**Comment by giuseppeg** [comment] 2018-12-13 08:31
@shYkiSto thanks for debugging this. There is nothing we can do about that except changing the prop name but that should happen in a major release which we are not planning. @rauchg / @timneutkens can make the call though.

**Comment by timneutkens** [comment] 2018-12-13 12:07
I'd be fine with changing the prop, it's just that we have to keep in mind to use a similar short name otherwise bundle size increases.

**Comment by giuseppeg** [comment] 2018-12-13 12:21
we can switch from 

```jsx
<Style styleId={123} css={''} />
```
to

```jsx
<Style id={123} children={''} />
```

**Comment by shYkiSto** [comment] 2018-12-14 03:07
@timneutkens @giuseppeg Let me know if you need any help making this change.

**Comment by giuseppeg** [comment] 2018-12-16 16:00
@shYkiSto if you have time I'd welcome a PR!

**Comment by giuseppeg** [comment] 2018-12-17 12:01
@webberwang if you remove the `jsx` attribute you are opting out styled-jsx :)

**Comment by lucifer1004** [comment] 2018-12-23 05:49
Downgrade `babel-plugin-styled-components` to `1.8.0` worked. Mark here to see the progress of this problem.

**Closed** 2018-12-27 07:53 UTC

**Comment by jota12x** [comment] 2019-01-15 19:07
@lucifer1004's solution worked for me as well. Thanks :)
