### ISSUE TITLE
Conflict with transform-react-inline-elements plugin

### ISSUE THREAD

**Issue by romainneutron** [zeit/styled-jsx#84] opened 2017-01-20 14:21 UTC
When using the `transform-react-inline-elements` alongside the `style-jsx` plugin, the result is broken, see:

```html
<html>
    <body>
        <div id="app"></div>
    </body>
    <script src="app.js"></script>
</html>
```

```jsx
import React from 'react';
import { render } from 'react-dom';

function Component2() {
    return (
        <div>
            <style jsx>{`
                p {
                    color: red;
                }
            `}</style>
            <p>{'This should be red'}</p>
        </div>
    );
}

function Component1() {
    return (
        <div>
            <p>{'This should be black'}</p>
            <Component2 />
        </div>
    );
}

render(<Component1 />, document.getElementById('app'));
```

When using webpack configuration:
```json
  {
      "presets": [
        ["es2015", { "modules": false }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "styled-jsx/babel",
      ]
    }
```
![image](https://cloud.githubusercontent.com/assets/137574/22152595/f8d4c608-df23-11e6-8cdf-3b81e3f0342d.png)

When using webpack configuration:
```json
  {
      "presets": [
        ["es2015", { "modules": false }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "transform-react-inline-elements",
        "styled-jsx/babel",
      ]
    }
```
![image](https://cloud.githubusercontent.com/assets/137574/22152604/084eed66-df24-11e6-8c28-a7ebeb6171d2.png)

**Comment by romainneutron** [comment] 2017-01-20 16:06
(and yes, I've tried to revert plugin order)

**Comment by giuseppeg** [comment] 2017-03-30 07:33
Closing this because it is a duplicate of #85 in a way

**Closed by giuseppeg** 2017-03-30 07:33 UTC
Labels: discussion, question
