### ISSUE TITLE
building components library with styled-jsx - to consume in AMP project

### ISSUE THREAD

**Issue by iliran11** [zeit/styled-jsx#564] opened 2019-06-18 07:59 UTC
Hi,
I have built a component library according to this article:
https://medium.com/@tomaszmularczyk89/guide-to-building-a-react-components-library-with-rollup-and-styled-jsx-694ec66bd2

I tried to consume it in regular next.js project - it works.
Then - I tried to consume it in next.js project [with AMP](https://nextjs.org/blog/next-8-1#what-is-amp) - it doesn't work. 

Maybe a hint for the root problem - 
- On regular next.js project - each component creates its `<style>...</style>` tag.
- On AMP project there is a single `<style amp-custom>...</style amp-custom>` with missing styles.

**Comment by timneutkens** [comment] 2019-06-18 23:23
Duplicate of https://github.com/zeit/next.js/issues/7595

**Closed by timneutkens** 2019-06-18 23:23 UTC

**Comment by timbielawski** [comment] 2019-07-29 15:12
you have more than one style tag?
